name: ERP Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # <- will run on your Ubuntu server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Restart frontend service
        run: sudo systemctl restart erp-frontend
